dependencies:
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.89
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: stable/elastic-stack
  version: 1.5.0
  repository: http://chartmuseum.jenkins-x.io
  alias: efk