PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild: {}
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: 34.76.149.193.nip.io
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global: {}
prow: {}
efk:
  kibana:
    env:
      ELASTICSEARCH_URL: http://efk-elasticsearch-client:9200
    ingress:
      enabled: true
      hosts:
        - kibana.34.76.149.193.nip.io
      annotations:
        kubernetes.io/ingress.class: nginx
    dashboardImport:
      dashboards: {"_id": "10d1f2b0-5157-11e9-96a5-e72ffec8361d","_type": "dashboard","_source": {"title": "Default","hits": 0,"description": "","panelsJSON": "[{\"embeddableConfig\":{},\"gridData\":{\"h\":11,\"i\":\"3\",\"w\":15,\"x\":15,\"y\":0},\"id\":\"f2884e40-5155-11e9-96a5-e72ffec8361d\",\"panelIndex\":\"3\",\"type\":\"visualization\",\"version\":\"6.6.0\"},{\"embeddableConfig\":{},\"gridData\":{\"h\":11,\"i\":\"4\",\"w\":18,\"x\":30,\"y\":0},\"id\":\"30fb3e80-5156-11e9-96a5-e72ffec8361d\",\"panelIndex\":\"4\",\"type\":\"visualization\",\"version\":\"6.6.0\"},{\"embeddableConfig\":{},\"gridData\":{\"h\":16,\"i\":\"5\",\"w\":48,\"x\":0,\"y\":11},\"id\":\"93e0c790-5156-11e9-96a5-e72ffec8361d\",\"panelIndex\":\"5\",\"type\":\"visualization\",\"version\":\"6.6.0\"},{\"embeddableConfig\":{},\"gridData\":{\"h\":11,\"i\":\"6\",\"w\":15,\"x\":0,\"y\":0},\"id\":\"8b7c4d00-5155-11e9-96a5-e72ffec8361d\",\"panelIndex\":\"6\",\"type\":\"visualization\",\"version\":\"6.6.0\"},{\"embeddableConfig\":{\"vis\":{\"legendOpen\":true}},\"gridData\":{\"h\":15,\"i\":\"7\",\"w\":24,\"x\":0,\"y\":27},\"id\":\"93bd4e20-5163-11e9-96a5-e72ffec8361d\",\"panelIndex\":\"7\",\"type\":\"visualization\",\"version\":\"6.6.0\"},{\"embeddableConfig\":{},\"gridData\":{\"h\":27,\"i\":\"8\",\"w\":48,\"x\":0,\"y\":42},\"id\":\"96431c60-5168-11e9-96a5-e72ffec8361d\",\"panelIndex\":\"8\",\"type\":\"search\",\"version\":\"6.6.0\"},{\"embeddableConfig\":{},\"gridData\":{\"h\":15,\"i\":\"9\",\"w\":24,\"x\":24,\"y\":27},\"id\":\"fcae9e40-5170-11e9-96a5-e72ffec8361d\",\"panelIndex\":\"9\",\"type\":\"visualization\",\"version\":\"6.6.0\"}]","optionsJSON": "{\"darkTheme\":false,\"hidePanelTitles\":false,\"useMargins\":true}","version": 1,"timeRestore": false,"kibanaSavedObjectMeta": {"searchSourceJSON": "{\"query\":{\"language\":\"lucene\",\"query\":\"\"},\"filter\":[]}"}}}
  fluentd-elasticsearch:
    elasticsearch:
      host: efk-elasticsearch-client
      logstash_prefix: fluentd-${record['kubernetes']['namespace_name']}
logstash:
  enabled: false
fluentd-elasticsearch:
  enabled: true